Type Conversions
javascript-tutorial/ro.javascript.info pull request #141
Opened 2022-11-26 03:21 UTC by Gabitzzz

2022-11-26 03:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ro.javascript.info?pullRequest=141) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ro.javascript.info?pullRequest=141) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ro.javascript.info?pullRequest=141) it.</sub>

2022-11-26 06:46 UTC, bogdanbacosca requested changes
Per total traducerea este excelentă.
Cea mai des întâlnită greșeală a fost lipsa de diacritice.
Unele sugestii sunt subiective și opționale, putem discuta despre ele.

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Majoritatea timpului, operatorii si funcțiile convertesc automat valorile date catre tipul corect.
Foarte bine. Singurul lucru greșit aici este că lipsesc diacritice din: "și" și "către"

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +De exemplu, `alert` convertește automat orice valoare catre un șir pentru a o arăta. Operațiile matematice convertesc valorile catre numere.
Sugestie:

```suggestion
De exemplu, `alert` convertește automat orice valoare către un șir pentru a o arăta. Operațiile matematice convertesc valorile în numere.
```

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Există și cazuri unde este nevoie sa convertim explicit o valoare către tipul așteptat.
Sugestii minore:
- Cuvântul "also" nu este încorporat în traducere
- Semn diacritic lipsă

```suggestion
De asemenea există și cazuri unde este nevoie să convertim explicit o valoare către tipul așteptat. 
```

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
>  ```smart header="Not talking about objects yet"
Acesta este un #header, poate fi tradus

```suggestion
```smart header="Nu vorbim despre obiecte încă"
```

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Totodată, putem apela funcța `String(value)` pentru a converti o valoare către un șir
Sugestiile în afară de `funcția` sunt subiective.

```suggestion
Totodată putem apela funcția `String(value)` pentru a converti o valoare într-un șir
```

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +value = String(value); // acum valoarea este un "adevărat" șir
Părere:
string "true" vs "true" string au însemnătăți diferite
în acest caz termenul tehnic tradus ca șir poate cauza puțină confuzie. În aceste cazuri nu e greșit să folosim termeni tehnici fără să-i traducem, câteodată chiar este de preferat.

```suggestion
value = String(value); // acum valoarea este un șir(string?): "adevărat"
```

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Conversia unui șir este destul de evidentă. Un `false` devine `"false"`, `null` devine `"null"`, etc.
Este mai fidel cu originalul așa?

```suggestion
Conversia unui șir este în mare parte evidentă. Un `false` devine `"false"`, `null` devine `"null"`, etc.
```

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Conversia numerică se petrece in funcții și expresii matematice automat.
```suggestion
Conversia numerică se petrece în funcții și expresii matematice automat.
```

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +alert( "6" / "2" ); // 3, șirurile sunt convertite către numere
Sugestie opțională/subiectivă
```suggestion
alert( "6" / "2" ); // 3, șirurile sunt convertite în numere
```

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +| `string` | Spațiile goale de la ïnceput și sfârșit sunt eliminate. Daca șirul rămas este gol, rezultatul este `0`. Altfel numărul este "citit" din șir . O eroare transmite `NaN`. |
```suggestion
| `string` | Spațiile goale de la ïnceput și sfârșit sunt eliminate. Daca șirul rămas este gol, rezultatul este `0`. Altfel numărul este "citit" din șir. O eroare transmite `NaN`. |
```

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +alert( Number("123z") );      // NaN (eroare la citirea unui numar la "z")
```suggestion
alert( Number("123z") );      // NaN (eroare la citirea unui număr la "z")
```

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Va rugăm sa notați faptul că `null` și `undefined` se comportă diferit aici: `null` devine 0, în timp ce `undefined` devine `NaN`.
```suggestion
Va rugăm să notați faptul că `null` și `undefined` se comportă diferit aici: `null` devine 0, în timp ce `undefined` devine `NaN`.
```

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Cei mai mulți operatori matematici execută o astfel de conversie, vom vedea aceasta in capitolul următor.
```suggestion
Cei mai mulți operatori matematici execută o astfel de conversie, vom vedea aceasta în capitolul următor.
```

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Are loc in operațiile logice (mai tarziu vom cunoaște teste condiționale si alte lucruri similare) dar poate fi executată specific cu o apelare la `Boolean(value)`.
S-ar potrivi mai bine întâlni în loc de cunoaște? meet !== knowledge
Cred că "also" ar putea fi tradus ca "de asemenea".

```suggestion
Are loc în operațiile logice (mai târziu vom întâlni teste condiționale și alte lucruri similare) dar poate de asemenea fi executată specific cu o apelare la `Boolean(value)`.
```

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +- Valorile care sunt "goale" intuitiv, ca și `0`, un șir gol, `null`, `undefined`, and `NaN`, devin `false`.
```suggestion
- Valorile care sunt "goale" intuitiv, ca și `0`, un șir gol, `null`, `undefined`, și `NaN`, devin `false`.
```

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Alte limbaje (anume PHP) trateaza `"0"` ca și `false`. Dar in JavaScript, un șir ne-gol este întotdeauna `true`.
```suggestion
Alte limbaje (anume PHP) tratează `"0"` ca și `false`. Dar în JavaScript, un șir ne-gol este întotdeauna `true`.
```

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +**`Conversia Șirului`** -- Apare când afișăm ceva. Poate fi executată cu `String(value)`. Aceasta conversia la șir este destul de evidentă pentru pentru valori primitive.
usually == de obicei

```suggestion
**`Conversia Șirului`** -- Apare când afișăm ceva. Poate fi executată cu `String(value)`. Conversia la șir este de obicei destul de evidentă pentru valori primitive.
```

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +**`Conversia Numerică`** -- Apare în operațiile matematica. Poate fi executată cu `Number(value)`.
```suggestion
**`Conversia Numerică`** -- Apare în operațiile matematice. Poate fi executată cu `Number(value)`.
```

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +| `string` | Șirul este citit "așa cum este", spațiile goale din ambele părți sunt ignorate. Un șir gol devine `0`. O eroare devine `NaN`. |
S-a folosit **transmite** mai sus. E perfect și aici. 👍️

```suggestion
| `string` | Șirul este citit "așa cum este", spațiile goale din ambele părți sunt ignorate. Un șir gol devine `0`. O eroare transmite `NaN`. |
```

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +**`Conversia Boolean`** -- Apare in operațiile logice. Poate fi executată cu `Boolean(value)`.
```suggestion
**`Conversia Boolean`** -- Apare în operațiile logice. Poate fi executată cu `Boolean(value)`.
```

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> -Objects aren't covered here. We'll return to them later in the chapter <info:object-toprimitive> that is devoted exclusively to objects after we learn more basic things about JavaScript.
Linia 151 din traducere începe la 150 în articolul original. Nu e o problemă mare dar bine de știut. Undeva s-au folosit cuvinte mai lungi (e normal într-o traducere) dar e bine pe cât posibil să păstrăm aceleași linii. 
Asta face bine când bot-ul adaugă elemente noi din versiunea en.

2022-11-26 06:46 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Obiectele nu sunt acoperite aici. Ne vom întoarce la ele mai târziu in capitolul <info:object-toprimitive> ce este devotat exclusiv obiectelor dupa ce învățăm mai multe lucruri elementare despre Java
```suggestion
Obiectele nu sunt acoperite aici. Ne vom întoarce la ele mai târziu în capitolul <info:object-toprimitive> ce este devotat exclusiv obiectelor după ce învățăm mai multe lucruri elementare despre JavaScript.
```

2022-11-26 07:02 UTC, bogdanbacosca commented
@Gabitzzz Am deschis un PR în versiunea originală `en` cu o sugestie din această traducere. Îl poți găsi aici: <https://github.com/javascript-tutorial/en.javascript.info/pull/3278/files>

2022-11-27 01:05 UTC, Gabitzzz reviewed
Modificari

2022-11-27 01:11 UTC, Gabitzzz commented
/done

2022-11-27 01:26 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Majoritatea timpului, operatorii si funcțiile convertesc automat valorile date catre tipul corect.
Lipsește semnul diacritic `către`

2022-11-27 01:48 UTC, bogdanbacosca requested changes
99% gata. Lipsesc doar cateva diacritice. Perfect!

2022-11-27 01:48 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +| `string` | Spațiile goale de la ïnceput și sfârșit sunt eliminate. Daca șirul rămas este gol, rezultatul este `0`. Altfel numărul este "citit" din șir. O eroare transmite `NaN`. |
```suggestion
| `string` | Spațiile goale de la ïnceput și sfârșit sunt eliminate. Dacă șirul rămas este gol, rezultatul este `0`. Altfel numărul este "citit" din șir. O eroare transmite `NaN`. |
```

2022-11-27 01:48 UTC, bogdanbacosca commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Majoritatea timpului, operatorii si funcțiile convertesc automat valorile date catre tipul corect.
```suggestion
Majoritatea timpului, operatorii si funcțiile convertesc automat valorile date către tipul corect.
```

2022-11-27 01:55 UTC, bogdanbacosca approved these changes
Overall quite a good job, imagine 100 people like us doing this - insane! I really appreciate it.

2022-11-27 01:56 UTC, merged