Logical operators
javascript-tutorial/ro.javascript.info pull request #185
Opened 2023-05-13 12:47 UTC by Cr3yZe

2023-05-14 21:27 UTC, bogdanbacosca requested changes
Am verificat toate task-urile și am propus cateva schimbări.
După ce te-ai uitat pe sugestii, înainte de următorul review te rog să te mai uiți odată și peste articol. 👍

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/1-alert-null-2-undefined/task.md
> +# Care este rezultatul lui ORI?
```suggestion
# Care este rezultatul lui OR?
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/2-alert-or/solution.md
> +Metoda `alert` nu returnează o valoare. Prin alte cuvinte, returnează `undefined`.
```suggestion
Apelul către `alert` nu returnează o valoare. Sau, prin alte cuvinte, returnează `undefined`.
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/2-alert-or/solution.md
> +1. Primul ORI `||` evaluează operantul din stânga sa `alert(1)`. Acesta afișează primul mesaj cu `1`.
```suggestion
1. Primul OR `||` evaluează operantul din stânga sa `alert(1)`. Aceasta afișează primul mesaj cu `1`.
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/2-alert-or/solution.md
> +2. `alert` întoarce `undefined`, prin urmare, ORI merge la cel de al doilea operant, deaorece caută o valoare truthy.
```suggestion
2. `alert` întoarce `undefined`, așa că OR merge la al doilea operand căutând o valoare truthy. 
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/2-alert-or/solution.md
> +3. Cel de al doilea operant `2` este truthy, așa că execuția este oprită, `2` este returnat fiind afișat de către `alert`-ul  exterior.
```suggestion
3. Cel de al doilea operand `2` este truthy, așa că execuția este oprită, `2` este returnat fiind afișat de către `alert`-ul  exterior.
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/2-alert-or/task.md
> +# Care este rezultatul metodelor de tip alert combinate prin ORI?
```suggestion
# Care este rezultatul alertelor combinate prin OR?
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/3-alert-1-null-2/solution.md
> +Răspunsul: `null`, deoarece este prin valoare falsy din șir.
```suggestion
Răspunsul: `null`, deoarece este prima valoare falsy din listă.
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/2-alert-or/solution.md
> +Răspunsul este: prima dată `1`, iar apoi `2`.
```suggestion
Răspunsul: prima dată `1`, iar apoi `2`.
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/3-alert-1-null-2/task.md
> +# Care este rezultatul lui ȘI?
```suggestion
# Care este rezultatul lui AND?
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/4-alert-and/task.md
> +# Care este rezultatul metodelor de tip aler combinate cu ȘI?
```suggestion
# Care este rezultatul alertelor combinate cu AND?
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/4-alert-and/task.md
> +Ce va afișa codul de mai jos?
```suggestion
Ce va afișa acest cod?
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/5-alert-and-or/solution.md
> +Răspunsul este: `3`
```suggestion
Răspunsul: `3`.
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/5-alert-and-or/solution.md
> +Prioritatea lui ȘI `&&` este mai mare decât cea a lui ORI `||`, așa că `&&` executat primul.
```suggestion
Prioritatea lui AND `&&` este mai mare decât cea a lui OR `||`, așa că se execută primul.
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/5-alert-and-or/solution.md
> +În acest caz, rezultatul este prima valoare truthy: `3`.
```suggestion
Acum rezultatul este prima valoare truthy: `3`.

```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/5-alert-and-or/task.md
> +# Rezultatul dintre ORI ȘI ORI
```suggestion
# Rezultatul lui OR AND OR
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/6-check-if-in-range/task.md
> +Scrie of condiție `if` care verifică dacă `age` se încadrează între valorile `14` și `90`, inclusiv.
```suggestion
Scrie o condiție `if` care verifică dacă `age` se încadrează între valorile `14` și `90` inclusiv. 
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/6-check-if-in-range/task.md
> +”Inclusiv” înseamnă că `age` poate fi de asemenea și `14` sau `90`.
```suggestion
"Inclusiv" înseamnă că `age` poate fi de asemenea `14` sau `90`.
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/7-check-if-out-range/task.md
> +# Verifică intervalul din afara.
```suggestion
# Verifică intervalul din afară
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/7-check-if-out-range/task.md
> +Scrie o condiție `if` care verifică dacă `age` nu este cuprins înte `14` și `90`, inclusiv.
```suggestion
Scrie o condiție `if` care verifică dacă `age` NU este cuprins înte `14` și `90` inclusiv. 
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/7-check-if-out-range/task.md
> +Creează două variante: în prima să folosești NU `!`, iar în ceea de-a doua să nu.
```suggestion
Creează două variante: în prima să folosești NOT `!`, iar în ceea de-a doua -- să nu.
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/8-if-question/solution.md
> +Răspuns: primul și al treilea vor fi afișate.
```suggestion
Răspuns: primul și al treilea se vor executa.
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/9-check-login/task.md
> +Dacă vizitatorul introduce `"Admin"`, atunci `prompt` pentru o parolă, dacă inputul este gol sau `key:Esc` -- afișați "Anulat", dacă este un alt string -- afișați "I don't know you".
```suggestion
Dacă vizitatorul introduce `"Admin"`, atunci `prompt` pentru o parolă, dacă inputul este gol sau `key:Esc` -- afișați "Anulat", dacă este un alt string -- afișați "Nu te cunosc".
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/9-check-login/task.md
> +- Dacă inputul este egal cu "TheMaster", atunci afișează "Welcome!",
```suggestion
- Dacă este egal cu "TheMaster", atunci afișează "Welcome!",
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/9-check-login/task.md
> +- Dacă este un alt string -- afișează "Wrong password"
```suggestion
- Dacă este un alt string -- afișează "Parolă greșită"
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/9-check-login/task.md
> +- Dacă este un string gol sau inputul este anulat, afișează "Canceled"
```suggestion
- Dacă este un string gol sau inputul este anulat, afișează "Anulat"
```

2023-05-14 21:27 UTC, bogdanbacosca commented on 1-js/02-first-steps/11-logical-operators/9-check-login/task.md
> +Vă rugăm folosiți blocuri `if` indentate. Aveți în vedere lizibilitatea generală a codului.
```suggestion
Vă rugăm folosiți blocuri `if` nested. Aveți în vedere lizibilitatea generală a codului.
```

2023-05-14 21:27 UTC, bogdanbacosca requested changes
Am verificat toate task-urile și am propus cateva schimbări.
După ce te-ai uitat pe sugestii, înainte de următorul review te rog să te mai uiți odată și peste articol. 👍

2023-07-14 14:45 UTC, Cr3yZe commented
/done

2023-08-25 08:47 UTC, Cr3yZe commented
"/done"

2023-09-06 06:50 UTC, bogdanbacosca approved these changes
Aprobat. Mulțumesc pentru contribuție și pentru efortul depus. 😁

2023-09-06 06:52 UTC, merged