Symbol type
javascript-tutorial/ro.javascript.info pull request #44
Opened 2019-12-24 12:23 UTC by armino-dev

I think that's it for this year :).
Happy holidays everyone!

2019-12-27 13:23 UTC, lighthousand commented
Happy holidays to you, too ! 🍾 🎉

2020-01-06 10:15 UTC, lighthousand commented on 1-js/04-object-basics/03-symbol/article.md
> +De exemplu, următoare instrucțiune `alert` va genera o eroare:
Typo : 'următoare' -> 'următoarea'

2020-01-21 14:26 UTC, lighthousand requested changes

2020-01-21 14:26 UTC, lighthousand commented on 1-js/04-object-basics/03-symbol/article.md
> +    Dacă vrem să adăugăm o proprietate într-un obiect care "aparține" altui script sau librărie, putem crea un simbol și îl putem folosi ca și proprietate cheie. O proprietate simbolică nu apare în `
Grammar suggestion :  "altui script sau librărie" --> "altui script sau biblioteci"

2020-01-21 14:26 UTC, lighthousand commented on 1-js/04-object-basics/03-symbol/article.md
> +Tehnic, simbolurile nu sunt 100% ascunse. Există metode ale limbajului JavaScript [Object.getOwnPropertySymbols(obj)](mdn:js/Object/getOwnPropertySymbols) care ne permit sa accesăm toate simbolurile.
Grammar suggestion : "librării" --> "biblioteci"

2020-01-21 14:57 UTC, armino-dev commented
/done

2020-01-21 15:17 UTC, armino-dev commented on 1-js/04-object-basics/03-symbol/article.md
> +De exemplu, următoare instrucțiune `alert` va genera o eroare:
This change was already made with commit 4eb75e5.

2020-01-23 09:28 UTC, lighthousand approved these changes
Good job!

2020-01-23 09:28 UTC, merged